baseURL = "https://mafr5102.github.io/marcfriedli.ch/"
languageCode = "en-us"
title = "Blowfish"
theme = "blowfish"
enableRobotsTXT = true

# Startseite korrekt anzeigen
disableKinds = ["sitemap", "taxonomy", "taxonomyTerm"]

